---
# Basic Setup of MySQL

#- name: Change mysqld.cnf to listen on all interfaces
#  shell: |
#    sed -i "s/^\(bind-address\s*=\s*\).*\$/\10.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
#  become: yes

- name: Install required packages
  dnf:
    name:
      - mysql-server
      - mysql-devel
      - python39
      - python39-devel
      - python39-pip
      - gcc
    state: latest

- name: Install required pip modules
  pip:
    name:
      - PyMySQL
    state: present
    executable: pip3

- name: Ensure mysql service is running
  systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Add .my.cnf to user home
  copy:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0755

#- name: Delete .my.conf
#  file:
#    path: /root/.my.cnf
#    state: absent

- name: Create wordpress database on the server
  mysql_db:
    name: wordpress
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Create wordpress user
  mysql_user:
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: wpuser
    password: "{{ dbpassword }}"
    priv: 'wordpress.*:ALL,GRANT'
    host: '%'
    state: present

#- name: Add logDNA tag
#  shell: logdna-agent -t database
#  become: yes

#- name: restart LogDNA
#  shell: service logdna-agent restart
#  become: yes

#- name: Install & Configure sysdig on DB server
#  shell: |
#      curl -sL https://ibm.biz/install-sysdig-agent | sudo bash -s -- --access_key {{ sysdig_key }}  -c ingest.us-south.monitoring.cloud.ibm.com --collector_port 6443 --secure true -ac "sysdig_capture_enabled: false" --tags role:database,location:us-south
#  become: yes
