# Generated by Tabular Terraform
resource "local_file" "inventory" {
filename = "/tmp/.schematics/hosts.ini"
content = <<EOT
[dbtier]
${module.backend.dbserver-zone1-ip}
${module.backend.dbserver-zone2-ip}
[webapptier]
${module.frontend.webappserver-zone1-ip} 
${module.frontend.webappserver-zone2-ip}
EOT
}
