# Generated by tabular-terraform
variable "centos-7-amd64" {
default = "r006-6f153a5d-6a9a-496d-8063-5c39932f6ded"
}
variable "debian-9-amd64" {
default = "r006-5e390f7b-0469-4ac1-b589-2fea307c1c5a"
}
variable "red-7-amd64" {
default = "r006-931515d2-fcc3-11e9-896d-3baa2797200f"
}
variable "red-7-amd64-sap-applications" {
default = "r006-f5387730-7a4b-4f71-9a85-13b05b137953"
}
variable "red-7-amd64-sap-hana" {
default = "r006-60d279a0-b328-40eb-a379-595ca53bee18"
}
variable "ubuntu-16-04-amd64" {
default = "r006-34ceeafe-fcc6-11e9-893a-57dde2f48a21"
}
variable "ubuntu-18-04-amd64" {
default = "r006-ed3f775f-ad7e-4e37-ae62-7199b4988b00"
}
variable "windows-2012-amd64" {
default = "r006-5f9568ae-792e-47e1-a710-5538b2bdfca7"
}
variable "windows-2012-r2-amd64" {
default = "r006-8bb3e8aa-b789-4292-8679-3564b3a9366a"
}
variable "windows-2016-amd64" {
default = "r006-54e9238a-ffdd-4f90-9742-7424eb2b9ff1"
}
