---
# Install & Configure mySQL for wordpress

- include: create-wordpress-db.yaml
- include: configure-replication-sourcedb.yaml
  when: zone == "us-south-1"
- include: configure-replication-replicadb.yaml
  when: zone == "us-south-2"
