---
# Basic Setup of MySQL

- name: Install required packages
  dnf:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: latest

- name: Install required pip modules
  pip:
    name:
      - PyMySQL
    state: present
    executable: pip3

- name: Ensure mariadb service is running
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Set mariadb root password
  mysql_user:
    login_user: root
    login_password: "{{ dbpassword }}" 
    user: root
    check_implicit_admin: true
    password: "{{ dbpassword }}"
    host: localhost

- name: Create wordpress database on the server
  mysql_db:
    name: wordpress
    login_user: root
    state: present

- name: Create wordpress user
  mysql_user:
    login_user: root
    name: wpuser
    password: "{{ dbpassword }}"
    priv: 'wordpress.*:ALL,GRANT'
    host: '%'
    state: present
