---
# Install mySQL for wordpress
# Configure mySQL sourcedb for wordpress

#- name: Install ansible python3 pymysql dependency
#  shell: pip install pymysql
#  become: yes
#

- name: List installed packages before
  shell: apt list --installed
  become: yes

- name: Install ansible python3 pymysql dependency
  become: yes
  pip:
    name: pymysql
    state: present

- name: List installed packages after
  shell: apt list --installed
  become: yes

- include: create-wordpress-db.yaml
- include: configure-replication-sourcedb.yaml
